name = "support-docs"
compatibility_date = "2025-12-22"
workers_dev = true
route = { pattern = "support2.letsbook.app/*", zone_name = "letsbook.app" }

[assets]
directory = "./build/"
not_found_handling = "404-page"

[env.staging]
name = "support-docs-staging"
route = { pattern = "support.letsbook.dev/*", zone_name = "letsbook.dev" }