name = "support-docs"
compatibility_date = "2025-12-22"
workers_dev = true
custom_domain = "support2.letsbook.app"

[assets]
directory = "./build/"
not_found_handling = "404-page"

[env.staging]
name = "support-docs-staging"
custom_domain = "support.letsbook.dev"